#! /usr/bin/env ruby

require 'chunky_png'

input, output = ARGV

fail "File #{input} does not exist." unless input && File.exist?(input)

image = ChunkyPNG::Image.from_file input

image.width.times do |x|
  image.height.times do |y|
    color_num = image[x, y]
    colors = ChunkyPNG::Color.to_truecolor_bytes color_num
    avg = colors.inject(&:+) / colors.size
    image[x, y] = ChunkyPNG::Color.rgb avg, avg, avg
  end
end

image.save output, interlace: true
